export const songs = [
  {
    title: "$orries",
    artist: "Peachy!",
    album: " Shiloh",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "1",
    img_src: "./songs_images/$orries_Cover (front)_e.jpg",
    src: "./songs/$orries.mp3",
  },
  {
    title: "[oops]",
    artist: "potsu",
    album: "[oops]",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/[oops]_Cover (front)_e.jpg",
    src: "./songs/[oops].mp3",
  },
  {
    title: "5:32pm",
    artist: "The Deli",
    album: "Vibes 2",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/5 32pm_Cover (front)_e.jpg",
    src: "./songs/5 32pm.mp3",
  },
  {
    title: "88 Keys",
    artist: "Oatmello",
    album: "Snapshots",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/88 Keys_Cover (front)_e.jpg",
    src: "./songs/88 Keys.mp3",
  },
  {
    title: "Affection",
    artist: "Jinsang",
    album: "Life",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Affection_Cover (front)_e.jpg ",
    src: "./songs/Affection.mp3",
  },
  {
    title: "Again",
    artist: "Wun Two",
    album: "Penthouse",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Again_Cover (front)_e.jpg",
    src: "./songs/Again.mp3",
  },
  {
    title: "Alone and Lonely",
    artist: "prxz",
    album: " Shiloh Dynasty",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "2",
    img_src: "./songs_images/Alone and Lonely_Cover (front)_e.jpg",
    src: "./songs/Alone and Lonely.mp3",
  },
  {
    title: "Baby You're Worth It",
    artist: "Kina",
    album: "Baby You're Worth It",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Baby You're Worth It_Cover (front)_e.jpg",
    src: "./songs/Baby You're Worth It.mp3",
  },
  {
    title: "Backpack City",
    artist: "Flovry",
    album: " tender spring",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "4",
    img_src: "./songs_images/ ",
    src: "./songs/Backpack City.mp3",
  },
  {
    title: "Beauty",
    artist: "eyeroze",
    album: "Heartless",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Beauty_Cover (front)_e.jpg",
    src: "./songs/Beauty.mp3",
  },
  {
    title: "Better Than He Can",
    artist: "Jennifer Flores",
    album: " Shiloh Dynasty",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "All My Love",
    img_src: "./songs_images/Better Than He Can_Cover (front)_e.jpg",
    src: "./songs/Better Than He Can.mp3",
  },
  {
    title: "Break My Heart Again",
    artist: "90degrees",
    album: "Break My Heart Again",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Break My Heart Again_Cover (front)_e.jpg",
    src: "./songs/Break My Heart Again.mp3",
  },
  {
    title: "Brightness",
    artist: "eyeroze",
    album: "Heartless",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Brightness_Cover (front)_e.jpg",
    src: "./songs/Brightness.mp3",
  },
  {
    title: "Call me",
    artist: "90sFlav",
    album: "Collection",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Call me_Cover (front)_e.jpg",
    src: "./songs/Call me.mp3",
  },
  {
    title: "Can We Kiss Forever?",
    artist: "Kina",
    album: " Adriana Proenza",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "1",
    img_src: "./songs_images/Can We Kiss Forever _Cover (front)_e.jpg",
    src: "./songs/Can We Kiss Forever .mp3",
  },
  {
    title: "Can't Love Myself",
    artist: "Monty Datta",
    album: " Mishaal",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "1",
    img_src: "./songs_images/Can't Love Myself_Cover (front)_e.jpg",
    src: "./songs/Can't Love Myself.mp3",
  },
  {
    title: "Can't Take My Eyes off You",
    artist: "Craymer",
    album: " AIIVAWN",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "1",
    img_src: "./songs_images/Can't Take My Eyes off You_Cover (front)_e.jpg",
    src: "./songs/Can't Take My Eyes off You.mp3",
  },
  {
    title: "Cigarettes and Sex",
    artist: "prxz",
    album: " Shiloh Dynasty",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "1",
    img_src: "./songs_images/Cigarettes and Sex_Cover (front)_e.jpg",
    src: "./songs/Cigarettes and Sex.mp3",
  },
  {
    title: "Coffee Breath",
    artist: "eyeroze",
    album: "Coffee Breath",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Coffee Breath_Cover (front)_e.jpg",
    src: "./songs/Coffee Breath.mp3",
  },
  {
    title: "controlla",
    artist: "Idealism",
    album: "rainy evening",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/controlla_Cover (front)_e.jpg",
    src: "./songs/controlla.mp3",
  },
  {
    title: "Cream",
    artist: "eyeroze",
    album: "Heartless",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Cream_Cover (front)_e.jpg",
    src: "./songs/Cream.mp3",
  },
  {
    title: "Day in Paris",
    artist: "Llusion",
    album: "Day in Paris",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Day in Paris_Cover (front)_e.jpg",
    src: "./songs/Day in Paris.mp3",
  },
  {
    title: "Daydreaming",
    artist: "eyeroze",
    album: "Heartless",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Daydreaming_Cover (front)_e.jpg",
    src: "./songs/Daydreaming.mp3",
  },
  {
    title: "Death Bed",
    artist: "Fets",
    album: " Koosen",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "Death Bed",
    img_src: "./songs_images/Death Bed_Cover (front)_e.jpg",
    src: "./songs/Death Bed.mp3",
  },
  {
    title: "drift...",
    artist: "junyii.",
    album: " Chill Children",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "3",
    img_src: "./songs_images/drift..._Cover (front)_e.jpg",
    src: "./songs/drift....mp3",
  },
  {
    title: "Evil Morty",
    artist: "Weegie",
    album: " Koosen",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "Evil Morty",
    img_src: "./songs_images/Evil Morty_Cover (front)_e.jpg",
    src: "./songs/Evil Morty.mp3",
  },
  {
    title: "Feblu",
    artist: "Flughand",
    album: "EXPEDITion Vol. 7: Moonloops",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Feblu_Cover (front)_e.jpg",
    src: "./songs/Feblu.mp3",
  },
  {
    title: "Fever Dream",
    artist: "Ethan Rebel",
    album: "Fever Dream",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Fever Dream_Cover (front)_e.jpg",
    src: "./songs/Fever Dream.mp3",
  },
  {
    title: "First Heartbreak",
    artist: "Flovry",
    album: " tender spring",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "3",
    img_src: "./songs_images/First Heartbreak_Cover (front)_e.jpg",
    src: "./songs/First Heartbreak.mp3",
  },
  {
    title: "French Inhale",
    artist: "[bsd.u]",
    album: "444",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/French Inhale_Cover (front)_e.jpg",
    src: "./songs/French Inhale.mp3",
  },
  {
    title: "Get You The Moon (feat. Snøw)",
    artist: "Kina",
    album: " Snøw",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "1",
    img_src: "./songs_images/Get You The Moon (feat. Snøw)_Cover (front)_e.jpg",
    src: "./songs/Get You The Moon (feat. Snøw).mp3",
  },
  {
    title: "Ghost Train Haze",
    artist: "BluntOne",
    album: "Forest Walk",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Ghost Train Haze_Cover (front)_e.jpg",
    src: "./songs/Ghost Train Haze.mp3",
  },
  {
    title: "Happiness",
    artist: "eyeroze",
    album: "Heartless",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/Happiness_Cover (front)_e.jpg",
    src: "./songs/Happiness.mp3",
  },
  {
    title: "hold up",
    artist: "eevee",
    album: "beat tape 06",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/hold up_Cover (front)_e.jpg",
    src: "./songs/hold up.mp3",
  },
  {
    title: "I Can't Help",
    artist: "Sarcastic Sounds",
    album: "I Can't Help",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/I Can't Help_Cover (front)_e.jpg",
    src: "./songs/I Can't Help.mp3",
  },
  {
    title: "I Don't Sleep",
    artist: "Sarcastic Sounds",
    album: "I Don't Sleep",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/I Don't Sleep_Cover (front)_e.jpg",
    src: "./songs/I Don't Sleep.mp3",
  },
  {
    title: "I Don't Trust Nobody",
    artist: "cucu",
    album: " Shiloh",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "1",
    img_src: "./songs_images/I Don't Trust Nobody_Cover (front)_e.jpg",
    src: "./songs/I Don't Trust Nobody.mp3",
  },
  {
    title: "I'll Bite Your Soul",
    artist: "SHRK",
    album: " Shiloh Dynasty",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "3",
    img_src: "./songs_images/I'll Bite Your Soul_Cover (front)_e.jpg",
    src: "./songs/I'll Bite Your Soul.mp3",
  },
  {
    title: "I'll Keep You Safe",
    artist: "sagun",
    album: "I'll Keep You Safe",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src: "./songs_images/I'll Keep You Safe_Cover (front)_e.jpg",
    src: "./songs/I'll Keep You Safe.mp3",
  },
  {
    title: "i'm closing my eyes (feat. shiloh)",
    artist: "potsu",
    album: "i'm closing my eyes (feat. shiloh)",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "",
    img_src:
      "./songs_images/i'm closing my eyes (feat. shiloh)_Cover (front)_e.jpg",
    src: "./songs/i'm closing my eyes (feat. shiloh).mp3",
  },
  {
    title: "I'm Drunk and Confused",
    artist: "eyeroze",
    album: " 90degrees",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "1",
    img_src: "./songs_images/I'm Drunk and Confused_Cover (front)_e.jpg",
    src: "./songs/I'm Drunk and Confused.mp3",
  },
  {
    title: "I'm Shy. I'm Anxious",
    artist: "prxz",
    album: " Shiloh Dynasty",
    music_text:
      "Chocolate bar marshmallow icing apple pie tiramisu. Brownie liquorice apple pie brownie soufflé cake tart soufflé chocolate cake. Cake cheesecake carrot cake jujubes bonbon dessert. Dessert lollipop jelly beans marzipan sugar plum sweet. Jujubes macaroon tootsie roll danish liquorice marshmallow muffin brownie bonbon. Apple pie sugar plum pie halvah dessert pie biscuit. Tootsie roll lollipop candy canes lollipop soufflé gummies cotton candy chocolate. Pudding ice cream bear claw topping pie gingerbread donut fruitcake ice cream. Caramels candy tiramisu liquorice tiramisu cupcake. Halvah marzipan bear claw danish donut. Pie candy muffin muffin croissant. Pie cake gummi bears gingerbread carrot cake marzipan chocolate jujubes. Tiramisu croissant sugar plum halvah macaroon candy canes biscuit sugar plum. Muffin caramels marshmallow sweet lollipop bonbon sesame snaps.",
    year: "3",
    img_src: "./songs_images/I'm Shy. I'm Anxious_Cover (front)_e.jpg",
    src: "./songs/I'm Shy. I'm Anxious.mp3",
  },
  {
    title: "I'm Sorry",
    artist: "Swell",
    album: " Shiloh",
    music_text: "Theres Still Us",
    year: "3",
    img_src: "./songs_images/I'm Sorry_Cover (front)_e.jpg",
    src: "./songs/I'm Sorry.mp3",
  },
  {
    title: "I'm Yours",
    artist: "Koosen",
    album: " Avocuddle",
    music_text: " Fets",
    year: "I'm Yours",
    img_src: "./songs_images/I'm Yours_Cover (front)_e.jpg",
    src: "./songs/I'm Yours.mp3",
  },
  {
    title: "In My Eyes",
    artist: "Beowülf",
    album: "In My Eyes",
    music_text: "1",
    year: "",
    img_src: "./songs_images/In My Eyes_Cover (front)_e.jpg",
    src: "./songs/In My Eyes.mp3",
  },
  {
    title: "infinity",
    artist: "Oatmello",
    album: "infinity",
    music_text: "1",
    year: "",
    img_src: "./songs_images/infinity_Cover (front)_e.jpg",
    src: "./songs/infinity.mp3",
  },
  {
    title: "I've Changed for You",
    artist: "Kina",
    album: " Madson Project.",
    music_text: "I've Changed for You",
    year: "1",
    img_src: "./songs_images/I've Changed for You_Cover (front)_e.jpg",
    src: "./songs/I've Changed for You.mp3",
  },
  {
    title: "Kiss",
    artist: "eyeroze",
    album: "Heartless",
    music_text: "3",
    year: "",
    img_src: "./songs_images/Kiss_Cover (front)_e.jpg",
    src: "./songs/Kiss.mp3",
  },
  {
    title: "Landing",
    artist: "dryhope",
    album: "White Oak",
    music_text: "2",
    year: "",
    img_src: "./songs_images/Landing_Cover (front)_e.jpg",
    src: "./songs/Landing.mp3",
  },
  {
    title: "Let Her Go",
    artist: "Sea Flap Flap",
    album: " Weegie",
    music_text: " Formal Chicken",
    year: "Let Her Go",
    img_src: "./songs_images/Let Her Go_Cover (front)_e.jpg",
    src: "./songs/Let Her Go.mp3",
  },
  {
    title: "Long",
    artist: "Shiloh Dynasty",
    album: " LofiCentral",
    music_text: " Stay Might",
    year: "Remixes",
    img_src: "./songs_images/Long_Cover (front)_e.jpg",
    src: "./songs/Long.mp3",
  },
  {
    title: "Loosing Interest",
    artist: "Timmies",
    album: "Passion & Confusion",
    music_text: "2",
    year: "",
    img_src: "./songs_images/Loosing Interest_Cover (front)_e.jpg",
    src: "./songs/Loosing Interest.mp3",
  },
  {
    title: "Losing Interest",
    artist: "itssvd",
    album: " Shiloh Dynasty",
    music_text: "Missing",
    year: "2",
    img_src: "./songs_images/Losing .Interest_Cover (front)_e.jpg",
    src: "./songs/Losing .Interest.mp3",
  },
  {
    title: "Losing Interest",
    artist: "itssvd",
    album: " Shiloh Dynasty",
    music_text: "Missing",
    year: "2",
    img_src: "./songs_images/Losing Interest(2)_Cover (front)_e.jpg",
    src: "./songs/Losing Interest.mp3",
  },
  {
    title: "Losing Interest",
    artist: "Inownlove",
    album: " Shiloh",
    music_text: "Feel Blue",
    year: "9",
    img_src: "./songs_images/Losing Interest(2)_Cover (front)_e.jpg",
    src: "./songs/Losing Interest(2).mp3",
  },
  {
    title: "Love Again",
    artist: "itssvd",
    album: " Shiloh Dynasty",
    music_text: "Missing",
    year: "1",
    img_src: "./songs_images/Love Again_Cover (front)_e.jpg",
    src: "./songs/Love Again.mp3",
  },
  {
    title: "Love Is More Depressing Than Depression",
    artist: "prxz",
    album: " Shiloh Dynasty",
    music_text: "Love Wounds",
    year: "7",
    img_src:
      "./songs_images/Love Is More Depressing Than Depression_Cover (front)_e.jpg",
    src: "./songs/Love Is More Depressing Than Depression.mp3",
  },
  {
    title: "Medieval",
    artist: "eyeroze",
    album: "Heartless",
    music_text: "9",
    year: "",
    img_src: "./songs_images/Medieval_Cover (front)_e.jpg",
    src: "./songs/Medieval.mp3",
  },
  {
    title: "Mirror Image",
    artist: "ENRA",
    album: " Sleepermane",
    music_text: "Tomorrows That Follow",
    year: "4",
    img_src: "./songs_images/Mirror Image_Cover (front)_e.jpg",
    src: "./songs/Mirror Image.mp3",
  },
  {
    title: "Miss You",
    artist: "Monty Datta",
    album: " Shiloh Dynasty",
    music_text: "Miss You",
    year: "1",
    img_src: "./songs_images/Miss You_Cover (front)_e.jpg",
    src: "./songs/Miss You.mp3",
  },
  {
    title: "Monday",
    artist: "eyeroze",
    album: "Heartless",
    music_text: "2",
    year: "",
    img_src: "./songs_images/Monday_Cover (front)_e.jpg",
    src: "./songs/Monday.mp3",
  },
  {
    title: "my new love",
    artist: "Elijah Who",
    album: "Gentle Boy",
    music_text: "12",
    year: "",
    img_src: "./songs_images/my new love_Cover (front)_e.jpg",
    src: "./songs/my new love.mp3",
  },
  {
    title: "nagashi",
    artist: "Idealism",
    album: "rainy evening",
    music_text: "5",
    year: "",
    img_src: "./songs_images/nagashi_Cover (front)_e.jpg",
    src: "./songs/nagashi.mp3",
  },
  {
    title: "Night Walk",
    artist: "xander.",
    album: "Found Memories",
    music_text: "1",
    year: "",
    img_src: "./songs_images/Night Walk_Cover (front)_e.jpg",
    src: "./songs/Night Walk.mp3",
  },
  {
    title: "Nightfall",
    artist: "eyeroze",
    album: "Heartless",
    music_text: "5",
    year: "",
    img_src: "./songs_images/Nightfall_Cover (front)_e.jpg",
    src: "./songs/Nightfall.mp3",
  },
  {
    title: "Nostalgia",
    artist: "eyeroze",
    album: "Heartless",
    music_text: "7",
    year: "",
    img_src: "./songs_images/Nostalgia_Cover (front)_e.jpg",
    src: "./songs/Nostalgia.mp3",
  },
  {
    title: "Not Even Her (feat. Shiloh)",
    artist: "Floreyyyy",
    album: " Shiloh",
    music_text: "Intimacy",
    year: "8",
    img_src: "./songs_images/Not Even Her (feat. Shiloh)_Cover (front)_e.jpg",
    src: "./songs/Not Even Her (feat. Shiloh).mp3",
  },
  {
    title: "Nova",
    artist: "mell-ø",
    album: "1 Am. Study Session",
    music_text: "6",
    year: "",
    img_src: "./songs_images/Nova_Cover (front)_e.jpg",
    src: "./songs/Nova.mp3",
  },
  {
    title: "Oblivion",
    artist: "Rufi-O",
    album: " Lily Potter",
    music_text: "Oblivion",
    year: "1",
    img_src: "./songs_images/Oblivion_Cover (front)_e.jpg",
    src: "./songs/Oblivion.mp3",
  },
  {
    title: "Our Adventures",
    artist: "xander.",
    album: "Found Memories",
    music_text: "3",
    year: "",
    img_src: "./songs_images/Our Adventures_Cover (front)_e.jpg",
    src: "./songs/Our Adventures.mp3",
  },
  {
    title: "over u",
    artist: "keshi",
    album: "over u",
    music_text: "1",
    year: "",
    img_src: "./songs_images/over u_Cover (front)_e.jpg",
    src: "./songs/over u.mp3",
  },
  {
    title: "Raindrops",
    artist: "Kupla",
    album: " j'san",
    music_text: "Memories",
    year: "2",
    img_src: "./songs_images/Raindrops_Cover (front)_e.jpg",
    src: "./songs/Raindrops.mp3",
  },
  {
    title: "Riptide",
    artist: "Poky",
    album: " Koosen",
    music_text: " Sea Flap Flap",
    year: "Riptide",
    img_src: "./songs_images/Riptide_Cover (front)_e.jpg",
    src: "./songs/Riptide.mp3",
  },
  {
    title: "Sad Vibes",
    artist: "eyeroze",
    album: "Sad Vibes",
    music_text: "1",
    year: "",
    img_src: "./songs_images/Sad Vibes_Cover (front)_e.jpg",
    src: "./songs/Sad Vibes.mp3",
  },
  {
    title: "Self Affray",
    artist: "fantompower",
    album: "infinite (i)",
    music_text: "7",
    year: "",
    img_src: "./songs_images/Self Affray_Cover (front)_e.jpg",
    src: "./songs/Self Affray.mp3",
  },
  {
    title: "Show and Prove",
    artist: "Es-K",
    album: "Trust The Process",
    music_text: "22",
    year: "",
    img_src: "./songs_images/Show and Prove_Cover (front)_e.jpg",
    src: "./songs/Show and Prove.mp3",
  },
  {
    title: "sincerely",
    artist: " yours",
    album: "Nohidea",
    music_text: "osho",
    year: "2",
    img_src: "./songs_images/sincerely, yours_Cover (front)_e.jpg",
    src: "./songs/sincerely.mp3",
  },
  {
    title: "sleep static",
    artist: "luvwn",
    album: "sleep static",
    music_text: "1",
    year: "",
    img_src: "./songs_images/sleep static_Cover (front)_e.jpg",
    src: "./songs/sleep static.mp3",
  },
  {
    title: "Snow & Sand",
    artist: "j'san",
    album: " Epektase",
    music_text: "1 Am. Study Session",
    year: "8",
    img_src: "./songs_images/Snow & Sand_Cover (front)_e.jpg",
    src: "./songs/Snow & Sand.mp3",
  },
  {
    title: "Snowman",
    artist: "WYS",
    album: "1 Am. Study Session",
    music_text: "1",
    year: "",
    img_src: "./songs_images/Snowman_Cover (front)_e.jpg",
    src: "./songs/Snowman.mp3",
  },
  {
    title: "Space Cadet",
    artist: "Philanthrope",
    album: " Sleepy Fish",
    music_text: "Chillhop Daydreams 2",
    year: "1",
    img_src: "./songs_images/Space Cadet_Cover (front)_e.jpg",
    src: "./songs/Space Cadet.mp3",
  },
  {
    title: "Stay Awake",
    artist: "Jennifer Flores",
    album: " Shiloh Dynasty",
    music_text: " LofiCentral",
    year: "All My Love",
    img_src: "./songs_images/Stay Awake_Cover (front)_e.jpg",
    src: "./songs/Stay Awake.mp3",
  },
  {
    title: "Sunday Afternoon",
    artist: "Oatmello",
    album: "Imperfections",
    music_text: "3",
    year: "",
    img_src: "./songs_images/Sunday Afternoon_Cover (front)_e.jpg",
    src: "./songs/Sunday Afternoon.mp3",
  },
  {
    title: "this girl",
    artist: "Elijah Who",
    album: "Gentle Boy",
    music_text: "4",
    year: "",
    img_src: "./songs_images/this girl_Cover (front)_e.jpg",
    src: "./songs/this girl.mp3",
  },
  {
    title: "Topaz",
    artist: "Oatmello",
    album: " Cloudchord",
    music_text: "Diamonds",
    year: "5",
    img_src: "./songs_images/Topaz_Cover (front)_e.jpg",
    src: "./songs/Topaz.mp3",
  },
  {
    title: "trust u",
    artist: "Monty Datta",
    album: " Kehard",
    music_text: "trust u",
    year: "1",
    img_src: "./songs_images/trust u_Cover (front)_e.jpg",
    src: "./songs/trust u.mp3",
  },
  {
    title: "walk but in a garden",
    artist: "Llusion",
    album: "walk but in a garden",
    music_text: "1",
    year: "",
    img_src: "./songs_images/walk but in a garden_Cover (front)_e.jpg",
    src: "./songs/walk but in a garden.mp3",
  },
  {
    title: "warm breeze",
    artist: "chief.",
    album: "today",
    music_text: "3",
    year: "",
    img_src: "./songs_images/warm breeze_Cover (front)_e.jpg",
    src: "./songs/warm breeze.mp3",
  },
  {
    title: "We Let Go",
    artist: "fantompower",
    album: "infinite (i)",
    music_text: "3",
    year: "",
    img_src: "./songs_images/We Let Go_Cover (front)_e.jpg",
    src: "./songs/We Let Go.mp3",
  },
  {
    title: "Why",
    artist: "eyeroze",
    album: "Heartless",
    music_text: "6",
    year: "",
    img_src: "./songs_images/Why_Cover (front)_e.jpg",
    src: "./songs/Why.mp3",
  },
  {
    title: "Wish I Was Better",
    artist: "Kina",
    album: " yaeow",
    music_text: "Wish I Was Better",
    year: "1",
    img_src: "./songs_images/Wish I Was Better_Cover (front)_e.jpg",
    src: "./songs/Wish I Was Better.mp3",
  },
  {
    title: "Wish You Were Mine",
    artist: "Sarcastic Sounds",
    album: "1 Am. Study Session",
    music_text: "14",
    year: "",
    img_src: "./songs_images/Wish You Were Mine_Cover (front)_e.jpg",
    src: "./songs/Wish You Were Mine.mp3",
  },
  {
    title: "Wishes",
    artist: "eyeroze",
    album: "Heartless",
    music_text: "1",
    year: "",
    img_src: "./songs_images/Wishes_Cover (front)_e.jpg",
    src: "./songs/Wishes.mp3",
  },
  {
    title: "With Somebody Else",
    artist: "Monty Datta",
    album: " Dhan",
    music_text: "With Somebody Else",
    year: "1",
    img_src: "./songs_images/With Somebody Else_Cover (front)_e.jpg",
    src: "./songs/With Somebody Else.mp3",
  },
  {
    title: "Yesterday",
    artist: "chief.",
    album: "Chillhop Daydreams",
    music_text: "2",
    year: "",
    img_src: "./songs_images/Yesterday_Cover (front)_e.jpg",
    src: "./songs/Yesterday.mp3",
  },
  {
    title: "Yoga",
    artist: "Llusion",
    album: "Yoga",
    music_text: "1",
    year: "",
    img_src: "./songs_images/Yoga_Cover (front)_e.jpg",
    src: "./songs/Yoga.mp3",
  },
  {
    title: "Young Dumb & Broke",
    artist: "90degrees",
    album: "Young Dumb & Broke",
    music_text: "1",
    year: "",
    img_src: "./songs_images/Young Dumb & Broke_Cover (front)_e.jpg",
    src: "./songs/Young Dumb & Broke.mp3",
  },
  {
    title: "Your Voice",
    artist: "Monty Datta",
    album: " Shiloh Dynasty",
    music_text: "Your Voice",
    year: "1",
    img_src: "./songs_images/Your Voice_Cover (front)_e.jpg",
    src: "./songs/Your Voice.mp3",
  },
];
